name: Deploy to Firebase (Hosting + Functions)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebase-config.js from secrets
        run: |
          mkdir -p public
          cat > public/firebase-config.js <<EOF
          window.__FBCONFIG__ = {
            apiKey: "${{ secrets.FB_API_KEY }}",
            authDomain: "${{ secrets.FB_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FB_PROJECT_ID }}",
            storageBucket: "${{ secrets.FB_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FB_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FB_APP_ID }}"
          };
          EOF

      - name: Install Functions deps
        working-directory: functions
        run: npm ci || npm i

      - name: Deploy (Hosting + Functions)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only hosting,functions --project "$FIREBASE_PROJECT_ID"
