name: Deploy to Firebase (Hosting + Functions)


on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]


jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout repo
uses: actions/checkout@v4


- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: '18'


- name: Install Firebase CLI
run: npm install -g firebase-tools


- name: Install Functions deps
working-directory: functions
run: npm ci || npm i


- name: Deploy (Hosting + Functions)
env:
FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
run: |
firebase deploy --only hosting,functions --project "$FIREBASE_PROJECT_ID"
